version: 0.2

env:
  variables:
    IMAGE_REPO: pavani84-hub/my-app

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub
      - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
  build:
    commands:
      - docker build -t $IMAGE_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag $IMAGE_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION $IMAGE_REPO:latest
  post_build:
    commands:
      - docker push $IMAGE_REPO:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $IMAGE_REPO:latest
