apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
     matchLabels: {app: my-app}
  template:
    metadata: {labels: {app: my-app}}
    spec:
      containers:
      - name: yourapp
        image: pavaniambica/my-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: yourapp-svc
spec:
  type: NodePort
  selector: {app: my-app}
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
